version: '3.3'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6100:6100"
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma
      - ./dev.db:/app/dev.db:rw
      - .:/app
      - /app/node_modules
